name: binder
channels:
  - conda-forge
channel_priority: strict

dependencies:
  - python=3.11
  - pip=25.*

  # FEniCSx stack (pin to compatible minor series)
  - fenics-dolfinx=0.9.*
  - mpi4py=4.1.*
  - petsc4py=3.23.*

  # common tools
  - numpy=2.3.*
  - scipy=1.16.*
  - matplotlib=3.10.*
  - pandas=2.3.*
  - jupyterlab=4.4.*
