name: binder
channels:
  - conda-forge
channel_priority: strict

dependencies:
  - python=3.11
  - pip

  # FEniCSx stack
  - fenics-dolfinx=0.9
  - mpi4py
  - petsc4py

  # common tools
  - numpy
  - scipy
  - matplotlib
  - pandas
  - jupyterlab

  # optional (only if you need it)
  # - gmsh
  # - python-gmsh
  # - pyvista
