name: fenicsx
channels:
  - pytorch
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _x86_64-microarch-level=4
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.14
  - aiosignal=1.4.0
  - alabaster=1.0.0
  - alsa-lib=1.2.14
  - anyio=4.9.0
  - anywidget=0.9.18
  - aom=3.9.1
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - arviz=0.22.0
  - asteval=1.0.6
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attr=2.5.1
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - binutils_impl_linux-64=2.44
  - binutils_linux-64=2.44
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blis=0.9.0
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.19.0
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=1.17.1
  - charls=2.4.2
  - charset-normalizer=3.4.2
  - chemicalfun=0.1.12
  - click=8.2.1
  - cmocean=4.0.3
  - colorama=0.4.6
  - colorspacious=1.1.2
  - comm=0.2.2
  - contourpy=1.3.2
  - corner=2.2.3
  - cppzmq=4.10.0
  - cpuonly=2.0
  - cpython=3.13.5
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.14
  - decorator=5.2.1
  - defusedxml=0.7.1
  - dill=0.4.0
  - docutils=0.21.2
  - double-conversion=3.3.1
  - eigen=3.4.0
  - emcee=3.1.6
  - entrypoints=0.4
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - fenics-basix=0.9.0
  - fenics-basix-nanobind-abi=0.2.1.13
  - fenics-dolfinx=0.9.0
  - fenics-ffcx=0.9.0
  - fenics-libbasix=0.9.0
  - fenics-libdolfinx=0.9.0
  - fenics-ufcx=0.9.0
  - fenics-ufl=2024.2.0
  - fftw=3.3.10
  - filelock=3.18.0
  - fltk=1.3.10
  - fmt=11.1.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.5
  - fqdn=1.5.1
  - freeglut=3.2.2
  - freeimage=3.18.0
  - freetype=2.13.3
  - frozenlist=1.7.0
  - fsspec=2025.7.0
  - future=1.0.0
  - gcc_impl_linux-64=13.3.0
  - gcc_linux-64=13.3.0
  - gems3k=4.4.2
  - giflib=5.2.2
  - gitdb=4.0.12
  - gitpython=3.1.45
  - gl2ps=1.4.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gmsh=4.13.1
  - graphite2=1.3.14
  - greenlet=3.2.3
  - h11=0.16.0
  - h2=4.2.0
  - h5netcdf=1.6.3
  - h5py=3.14.0
  - harfbuzz=11.2.1
  - hdf4=4.2.15
  - hdf5=1.14.6
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - hypre=2.32.0
  - icu=75.1
  - idna=3.10
  - imagecodecs=2025.3.30
  - imageio=2.37.0
  - imagesize=1.4.1
  - imath=3.1.12
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipyfilechooser=0.6.0
  - ipykernel=6.29.5
  - ipython=9.4.0
  - ipython_genutils=0.2.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=7.6.5
  - isoduration=20.11.0
  - jasper=4.2.5
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - json5=0.12.0
  - jsoncpp=1.9.6
  - jsonpointer=3.0.0
  - jsonschema=4.24.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.24.0
  - jupyter-cache=1.0.1
  - jupyter-lsp=2.2.5
  - jupyter-server-mathjax=0.2.6
  - jupyter_client=7.4.9
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab-git=0.8.2
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=1.1.11
  - jxrlib=1.1
  - kahip=3.19
  - kaldi=5.5.1112
  - kernel-headers_linux-64=5.14.0
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lazy-loader=0.4
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250512.1
  - libadios2=2.10.2
  - libaec=1.1.4
  - libamd=3.3.3
  - libavif16=1.3.0
  - libblas=3.9.0
  - libboost=1.86.0
  - libboost-devel=1.86.0
  - libboost-headers=1.86.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libbtf=2.3.2
  - libcamd=3.3.3
  - libcap=2.75
  - libcblas=3.9.0
  - libccolamd=3.3.4
  - libcholmod=5.3.1
  - libclang-cpp20.1=20.1.8
  - libclang13=20.1.8
  - libcolamd=3.3.4
  - libcups=2.3.3
  - libcurl=8.14.1
  - libde265=1.0.15
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.0
  - libfabric=2.2.0
  - libfabric1=2.2.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-devel_linux-64=13.3.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libheif=1.19.7
  - libhwloc=2.11.2
  - libhwy=1.3.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - libjxl=0.11.1
  - libklu=2.3.5
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm20=20.1.8
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libnl=3.11.0
  - libntlm=1.8
  - libogg=1.3.5
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpmix=5.0.8
  - libpng=1.6.50
  - libpq=17.5
  - libprotobuf=6.31.1
  - libptscotch=7.0.6
  - libraw=0.21.4
  - libsanitizer=13.3.0
  - libscotch=7.0.6
  - libsodium=1.0.20
  - libspqr=4.3.4
  - libsqlite=3.50.2
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsuitesparseconfig=7.10.1
  - libsystemd0=257.7
  - libtheora=1.1.1
  - libtiff=4.7.0
  - libtorch=2.7.1
  - libudev1=257.7
  - libumfpack=6.3.5
  - libuuid=2.38.1
  - libuv=1.51.0
  - libvorbis=1.3.7
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.10.0
  - libxml2=2.13.8
  - libzip=1.11.2
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - llvm-openmp=20.1.8
  - lmfit=1.3.4
  - loguru=0.7.3
  - lz4-c=1.10.0
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - mdit-py-plugins=0.4.2
  - mdurl=0.1.2
  - metis=5.1.0
  - mistune=3.1.3
  - mkl=2024.2.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpi=1.0
  - mpi4py=4.1.0
  - mpmath=1.3.0
  - msgpack-python=1.1.1
  - multidict=6.6.3
  - mumps-include=5.7.3
  - mumps-mpi=5.7.3
  - munkres=1.1.4
  - myst-nb=1.3.0
  - myst-parser=4.0.1
  - narwhals=2.0.1
  - nbclassic=1.3.1
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbdime=4.0.2
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.5
  - nlohmann_json=3.12.0
  - nodejs=24.4.1
  - notebook=6.5.7
  - notebook-shim=0.2.4
  - numpy=2.3.1
  - occt=7.8.1
  - odfpy=1.4.1
  - openexr=3.3.4
  - openfst=1.8.3
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openmpi=5.0.8
  - openpyxl=3.1.5
  - openssl=3.6.0
  - optree=0.17.0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.1
  - pandoc=3.7.0.2
  - pandocfilters=1.5.0
  - parmetis=4.0.3
  - parso=0.8.4
  - pcre2=10.45
  - petsc=3.23.4
  - petsc4py=3.23.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pixman=0.46.2
  - pkg-config=0.29.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.8
  - pooch=1.8.2
  - proj=9.6.2
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - propcache=0.3.1
  - psutil=7.0.0
  - psygnal=0.13.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.15
  - pure_eval=0.2.3
  - pybind11=3.0.0
  - pybind11-abi=11
  - pybind11-global=3.0.0
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - pyswarms=1.3.0
  - python=3.13.5
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-gmsh=4.13.1
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytorch=2.7.1
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyvista=0.45.2
  - pywavelets=1.9.0
  - pyyaml=6.0.2
  - pyzmq=27.0.0
  - qhull=2020.2
  - qt6-main=6.9.1
  - rapidjson=1.1.0.post20240409
  - rav1e=0.7.1
  - rdma-core=58.0
  - readline=8.2
  - referencing=0.36.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - roman-numerals-py=3.1.0
  - rpds-py=0.26.0
  - scalapack=2.2.0
  - scikit-image=0.25.2
  - scikit-learn=1.7.1
  - scipy=1.16.0
  - scooby=0.10.1
  - send2trash=1.8.3
  - setuptools=80.9.0
  - setuptools-scm=8.3.1
  - six=1.17.0
  - sleef=3.8
  - slepc=3.23.2
  - slepc4py=3.23.2
  - smmap=5.0.2
  - snappy=1.2.1
  - sniffio=1.3.1
  - snowballstemmer=3.0.1
  - soupsieve=2.7
  - spdlog=1.15.3
  - sphinx=8.2.3
  - sphinx-autodoc-typehints=3.2.0
  - sphinx-copybutton=0.5.2
  - sphinx-wagtail-theme=6.5.0
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - sqlalchemy=2.0.41
  - sqlite=3.50.2
  - stack_data=0.6.3
  - superlu=7.0.1
  - superlu_dist=9.1.0
  - svt-av1=3.0.2
  - sympy=1.14.0
  - sysroot_linux-64=2.34
  - tabulate=0.9.0
  - tbb=2021.13.0
  - terminado=0.18.1
  - thermofun=0.5.3
  - threadpoolctl=3.6.0
  - tifffile=2025.10.16
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - torchaudio=2.7.1
  - torchvision=0.22.0
  - torchvision-extra-decoders=0.0.2
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250708
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - typing_utils=0.1.0
  - tzdata=2025b
  - ucc=1.4.4
  - ucx=1.18.1
  - uncertainties=3.2.3
  - uri-template=1.3.0
  - urllib3=2.5.0
  - utfcpp=4.0.6
  - voila=0.5.9
  - vtk-base=9.4.2
  - wayland=1.24.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - websockets=15.0.1
  - widgetsnbextension=3.5.1
  - wrapt=1.17.2
  - wslink=2.3.4
  - x265=3.5
  - xarray=2025.7.1
  - xarray-einstats=0.9.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xgems=2.0.1
  - xkeyboard-config=2.45
  - xlwings=0.33.15
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxmu=1.2.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - yaml=0.2.5
  - yarl=1.20.1
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.4
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - altair==6.0.0
      - analytics-python==1.4.post1
      - annotated-types==0.7.0
      - astunparse==1.6.3
      - backoff==1.10.0
      - blinker==1.9.0
      - cachetools==6.2.6
      - chardet==5.2.0
      - cloudpickle==3.1.1
      - dask==2025.7.0
      - dataclasses-json==0.6.7
      - deepmerge==2.0
      - distributed==2025.7.0
      - faiss-cpu==1.12.0
      - flatbuffers==25.2.10
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.74.0
      - httpx-sse==0.4.1
      - jsonpatch==1.33
      - jsonpath-ng==1.7.0
      - jupyter-ai==2.31.6
      - jupyter-ai-chatgpt==0.5.0
      - jupyter-ai-magics==2.31.6
      - jupyterlab==4.4.9
      - jupyterlab-execute-time==3.2.0
      - jupyterlab-spreadsheet==0.4.2
      - jupyterlab-spreadsheet-editor==0.7.2
      - keras==3.11.2
      - langchain==0.3.27
      - langchain-community==0.3.28
      - langchain-core==0.3.75
      - langchain-text-splitters==0.3.9
      - langsmith==0.4.19
      - libclang==18.1.1
      - locket==1.0.0
      - markdown==3.8.2
      - marshmallow==3.26.1
      - ml-dtypes==0.5.3
      - monotonic==1.6
      - mypy-extensions==1.1.0
      - namex==0.1.0
      - nvidia-cublas-cu12==12.9.1.4
      - nvidia-cuda-cupti-cu12==12.9.79
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu12==12.9.86
      - nvidia-cuda-runtime-cu12==12.9.79
      - nvidia-cudnn-cu12==9.12.0.46
      - nvidia-cufft-cu12==11.4.1.4
      - nvidia-curand-cu12==10.3.10.19
      - nvidia-cusolver-cu12==11.7.5.82
      - nvidia-cusparse-cu12==12.5.10.65
      - nvidia-nccl-cu12==2.27.7
      - nvidia-nvjitlink-cu12==12.9.86
      - opt-einsum==3.4.0
      - orjson==3.11.3
      - partd==1.4.2
      - pip==25.2
      - plotly==5.24.1
      - ply==3.11
      - protobuf==6.31.1
      - pyarrow==23.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydantic-settings==2.10.1
      - pydeck==0.9.1
      - python-dotenv==1.1.1
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rich==14.1.0
      - sortedcontainers==2.4.0
      - streamlit==1.53.1
      - tblib==3.1.0
      - tenacity==9.1.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0rc0
      - termcolor==3.1.0
      - toml==0.10.2
      - toolz==1.0.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - watchdog==6.0.0
      - werkzeug==3.1.3
      - wheel==0.45.1
      - zict==3.0.0
prefix: /home/xi_b/miniforge3/envs/fenicsx
